# Generated by Django 5.1.5 on 2025-01-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('email', 'Email'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('textarea', 'Textarea'), ('file', 'File'), ('image', 'Image'), ('select', 'Select')], db_index=True, max_length=50),
        ),
    ]
