# Generated by Django 5.1.5 on 2025-01-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_column_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
