# Generated by Django 5.1.5 on 2025-01-30 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_alter_cell_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableapi',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_api', to='rest.table'),
        ),
    ]
