# Generated by Django 5.1.5 on 2025-01-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_tableapi_table_alter_tableapi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
